server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://wow-car-rental.c8qm8sy6o9um.us-east-1.rds.amazonaws.com:3306/wowdb
    username: admin
    password: DBfinalproject
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cly.backend.entity
  configuration:
    map-underscore-to-camel-case: true

swagger:
  enabled: true

jwt:
  header: Authorization
  secret: cly-db-project-backend
  #unit: minutes
  expireTime: 30


